$files = @(
'action-history'
'brushes\arrow001.gbr'
'brushes\badge001.gbr'
'brushes\badge002.gbr'
'brushes\cloud001.gbr'
'brushes\cloud002.gbr'
'brushes\damnicons_1.gbr'
'brushes\damnicons_10.gbr'
'brushes\damnicons_2.gbr'
'brushes\damnicons_3.gbr'
'brushes\damnicons_4.gbr'
'brushes\damnicons_5.gbr'
'brushes\damnicons_6.gbr'
'brushes\damnicons_7.gbr'
'brushes\damnicons_8.gbr'
'brushes\damnicons_9.gbr'
'brushes\floral1_brush_by hawksmont1.gbr'
'brushes\floral1_brush_by hawksmont2.gbr'
'brushes\floral1_brush_by hawksmont3.gbr'
'brushes\floral1_brush_by hawksmont4.gbr'
'brushes\floral1_brush_by hawksmont5.gbr'
'brushes\floral1_brush_by hawksmont6.gbr'
'brushes\floral1_brush_by hawksmont7.gbr'
'brushes\floral1_brush_by hawksmont8.gbr'
'brushes\floral1_brush_by hawksmont9.gbr'
'brushes\floral2_brush_by hawksmont1.gbr'
'brushes\floral2_brush_by hawksmont2.gbr'
'brushes\floral2_brush_by hawksmont3.gbr'
'brushes\floral2_brush_by hawksmont4.gbr'
'brushes\floral2_brush_by hawksmont5.gbr'
'brushes\floral2_brush_by hawksmont6.gbr'
'brushes\groove001.gbr'
'brushes\groove002.gbr'
'brushes\groove003.gbr'
'brushes\groove004.gbr'
'brushes\groove005.gbr'
'brushes\groove006.gbr'
'brushes\halftone001.gbr'
'brushes\halftonestar.gbr'
'brushes\honeycomb.gbr'
'brushes\honeycomb2.gbr'
'brushes\icon001.gbr'
'brushes\InnerUniverse_1.gbr'
'brushes\InnerUniverse_2.gbr'
'brushes\InnerUniverse_3.gbr'
'brushes\InnerUniverse_4.gbr'
'brushes\InnerUniverse_5.gbr'
'brushes\InnerUniverse_6.gbr'
'brushes\InnerUniverse_7.gbr'
'brushes\InnerUniverse_8.gbr'
'brushes\orb001.gbr'
'brushes\orb002.gbr'
'brushes\orb003.gbr'
'brushes\ribbon001.gbr'
'brushes\Rush_1.gbr'
'brushes\Rush_10.gbr'
'brushes\Rush_11.gbr'
'brushes\Rush_12.gbr'
'brushes\Rush_2.gbr'
'brushes\Rush_3.gbr'
'brushes\Rush_4.gbr'
'brushes\Rush_5.gbr'
'brushes\Rush_6.gbr'
'brushes\Rush_7.gbr'
'brushes\Rush_8.gbr'
'brushes\Rush_9.gbr'
'brushes\Sem título.gbr'
'brushes\Splatter Brush1.gbr'
'brushes\Splatter Brush10.gbr'
'brushes\Splatter Brush11.gbr'
'brushes\Splatter Brush2.gbr'
'brushes\Splatter Brush3.gbr'
'brushes\Splatter Brush4.gbr'
'brushes\Splatter Brush5.gbr'
'brushes\Splatter Brush6.gbr'
'brushes\Splatter Brush7.gbr'
'brushes\Splatter Brush8.gbr'
'brushes\Splatter Brush9.gbr'
'brushes\star002.gbr'
'brushes\starhalf.gbr'
'brushes\startrail.gbr'
'brushes\swirl001.gbr'
'brushes\swirls001.gbr'
'colorrc'
'contextrc'
'controllerrc'
'devicerc'
'dockrc'
'filters\GimpColorBalanceConfig.settings'
'filters\GimpCurvesConfig.settings'
'filters\GimpGegl-gegl-bloom-config.settings'
'filters\GimpGegl-gegl-channel-mixer-config.settings'
'filters\GimpGegl-gegl-color-temperature-config.settings'
'filters\GimpGegl-gegl-color-to-alpha-config.settings'
'filters\GimpGegl-gegl-dropshadow-config.settings'
'filters\GimpGegl-gegl-exposure-config.settings'
'filters\GimpGegl-gegl-focus-blur-config.settings'
'filters\GimpGegl-gegl-gaussian-blur-config.settings'
'filters\GimpGegl-gegl-high-pass-config.settings'
'filters\GimpGegl-gegl-hue-chroma-config.settings'
'filters\GimpGegl-gegl-lens-flare-config.settings'
'filters\GimpGegl-gegl-long-shadow-config.settings'
'filters\GimpGegl-gegl-median-blur-config.settings'
'filters\GimpGegl-gegl-oilify-config.settings'
'filters\GimpGegl-gegl-rgb-clip-config.settings'
'filters\GimpGegl-gegl-saturation-config.settings'
'filters\GimpGegl-gegl-shadows-highlights-config.settings'
'filters\GimpGegl-gegl-variable-blur-config.settings'
'filters\GimpGegl-gimp-colorize-config.settings'
'filters\GimpGegl-gimp-desaturate-config.settings'
'filters\GimpGegl-gimp-threshold-config.settings'
'filters\GimpHueSaturationConfig.settings'
'filters\GimpLevelsConfig.settings'
'gimprc'
'gtkrc'
'menurc'
'parasiterc'
'plug-ins\dbp'
'plug-ins\fix-ca'
'plug-ins\gimp-lqr-plugin'
'plug-ins\gimpmask'
'plug-ins\plugin-heal-selection.py'
'plug-ins\plugin-heal-transparency.py'
'plug-ins\plugin-map-style.py'
'plug-ins\plugin-render-texture.py'
'plug-ins\plugin-resynth-enlarge.py'
'plug-ins\plugin-resynth-fill-pattern.py'
'plug-ins\plugin-resynth-sharpen.py'
'plug-ins\plugin-uncrop.py'
'plug-ins\plug_in_lqr_iter'
'plug-ins\resynthesizer'
'plug-ins\resynthesizer-gui'
'plug-ins\separate'
'plug-ins\separate_import'
'plug-ins\streak'
'plug-ins\wavelet-denoise'
'plug-ins\webexport'
'sessionrc'
'splashes\photogimp-diolinux-splash.png'
'tags.xml'
'templaterc'
'themerc'
'tool-options\gimp-airbrush-tool'
'tool-options\gimp-align-tool'
'tool-options\gimp-brightness-contrast-tool'
'tool-options\gimp-bucket-fill-tool'
'tool-options\gimp-by-color-select-tool'
'tool-options\gimp-cage-tool'
'tool-options\gimp-clone-tool'
'tool-options\gimp-color-picker-tool'
'tool-options\gimp-convolve-tool'
'tool-options\gimp-crop-tool'
'tool-options\gimp-curves-tool'
'tool-options\gimp-dodge-burn-tool'
'tool-options\gimp-ellipse-select-tool'
'tool-options\gimp-eraser-tool'
'tool-options\gimp-flip-tool'
'tool-options\gimp-foreground-select-tool'
'tool-options\gimp-free-select-tool'
'tool-options\gimp-fuzzy-select-tool'
'tool-options\gimp-gegl-tool'
'tool-options\gimp-gradient-tool'
'tool-options\gimp-handle-transform-tool'
'tool-options\gimp-heal-tool'
'tool-options\gimp-ink-tool'
'tool-options\gimp-iscissors-tool'
'tool-options\gimp-levels-tool'
'tool-options\gimp-measure-tool'
'tool-options\gimp-move-tool'
'tool-options\gimp-mypaint-brush-tool'
'tool-options\gimp-offset-tool'
'tool-options\gimp-operation-tool'
'tool-options\gimp-paintbrush-tool'
'tool-options\gimp-pencil-tool'
'tool-options\gimp-perspective-clone-tool'
'tool-options\gimp-perspective-tool'
'tool-options\gimp-rect-select-tool'
'tool-options\gimp-rotate-tool'
'tool-options\gimp-scale-tool'
'tool-options\gimp-shear-tool'
'tool-options\gimp-smudge-tool'
'tool-options\gimp-text-tool'
'tool-options\gimp-threshold-tool'
'tool-options\gimp-transform-3d-tool'
'tool-options\gimp-unified-transform-tool'
'tool-options\gimp-vector-tool'
'tool-options\gimp-warp-tool'
'tool-options\gimp-zoom-tool'
'toolrc'
)
